### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gitanat** [RedFantom/simple-ocr-opencv#2]
As the sole author and copyright holder of simple-ocr-opencv, I hereby license the original version of this repository (as of git commit 8eeda373009033a9f32455dd711e486660d63b8c, at 2016-08-31) under the AGPL version 1 or later. The full license terms can be found on http://www.affero.org/oagpl.html
This license is applicable only to this specific version (git commit 8eeda373009033a9f32455dd711e486660d63b8c), and does not apply or grant any rights to any other existing or future derivative works of my authorship.

@RedFantom You might want to include a LICENSE file, as any changes you (or other people) do to the code will need to also be made available under the AGPL

**Comment by RedFantom** [comment]
@goncalopp 
I would much rather license it under the GNU AGPLv3, as it allows crosslicensing with GNU GPLv3. The Affero License you linked to even recommends using GNU AGPLv3 instead:

    Note: The GNU Affero General Public License version 3 has been released. It follows the same 
    basic structure as this license, but it is based on version 3 of the GNU GPL, and you can 
    combine modules released under GPLv3 and the GNU AGPLv3. If you were thinking about 
    releasing your software under this license, we recommend you use the GNU AGPLv3 instead. 

So unless you explicitly and exclusively want the Affero AGPL version 1 or greater, I would greatly appreciate it if you choose GNU AGPL version 1 or greater, as it allows for a bit more freedom in what programs this software would be possible to use. If you allow GNU AGPL version 1 or greater, I will add a LICENSE file and a notice in the README as soon as I possibly can.

**Comment by gitanat** [comment]
As I understand, licensing under "AGPLv1 or later" means you can use AGPLv2, which, in turn, also licenses it under GNU's AGPLv3. You're free to use the software under any of these, so if you actually prefer to have that on the LICENSE file, please feel free to do so.

**Comment by RedFantom** [comment]
The license was added to the `master` branch in commit 6a1b5c1. It's the GNU AGPLv3 license. Of course, technically users can also still claim their copies under the AGPLv1 and up, as you licensed your original under that license.
